name: Actions Workflow
on:
  - push

jobs:
  
  JavaScript-Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Actions
      # Every step can be gien by id so that it can be accessed by other stpes in job
        id: greet
      # Here I am using actions : username/repo-name@[version, commitSHA, branch-name]
        uses: actions/hello-world-javascript-action@v1
        # using with I can give input to actions. who-to-greet is the input key. For input keys look into actions document.
        with:
          who-to-greet: Actions
        # ${{}} using this we can access github variables. stpes gives us acess to any stpes in job and id gives access to that id and then output.<output> gives the output
        # for <output> check respective actions doc
      - name: Output
        run: echo "${{ steps.greet.outputs.time }}"
  
  CheckoutCode:
    runs-on: windows-latest
    # needs:
    #   - JavaScript-Hello
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Basic Commands
        run: |
          cd
          dir
        shell: cmd
      - name: Github variables
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
        shell: bash
      - name: Github variables
        run: |
          echo $GITHUB_SHA 
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
        shell: cmd
#  Github VARIABLES
# $GITHUB_SHA - Last commit hash value
# $GITHUB_REPOSITORY - username/repository_name
# $GITHUB_WORSPACE - cureent working directory where github code was checked out

