name: Solution List
on: 
  push:
    branches: [solution]

env:
  solutionList : >
    '[
    {"name":"solutionPath","path":"Project\\Build\\Licensing\\Licensing.sln","vsversion":"vs2017","usemsbuild":"false","buildconfig":"Release","buildplatform":"Win32"},
    {"name":"solutionPath","path":"Project\\Build\\Files\\WUGLibs.sln","vsversion":"vs2017","usemsbuild":"false","buildconfig":"Release","buildplatform":"Any CPU"}
    ]'
  workspace: D:\\
  

jobs:
  
  Check-Env-Variables: 
    runs-on: windows-latest
    steps:

      - name: Veify XML file
        run: ls ${workspace}
        shell: pwsh

      - name: Create XML file
        run: |
          powershell '$xmlWriter = New-Object System.XMl.XmlTextWriter("${workspace}\SolutionList.xml",$Null)'
          powershell '$xmlWriter.Formatting = "Indented"'
          powershell '$xmlWriter.Indentation = 1'
          powershell '$XmlWriter.IndentChar = "`t"'
          powershell '$xmlWriter.WriteStartDocument()'
          powershell '$xmlWriter.WriteStartElement("build")'
          powershell '$xmlWriter.WriteEndElement()'
          powershell '$xmlWriter.WriteEndDocument()'
          powershell '$xmlWriter.Flush()'
          powershell '$xmlWriter.Close()'
        shell: bash

      - name: Veify XML file
        run: ls ${workspace}
        shell: pwsh
