name: Solution List
on: 
  push:
    branches: [solution]

env:
  solutionList : >
    '[
    {"name":"solutionPath","path":"Project\\Build\\Licensing\\Licensing.sln","vsversion":"vs2017","usemsbuild":"false","buildconfig":"Release","buildplatform":"Win32"},
    {"name":"solutionPath","path":"Project\\Build\\Files\\WUGLibs.sln","vsversion":"vs2017","usemsbuild":"false","buildconfig":"Release","buildplatform":"Any CPU"}
    ]'
  workspace: D:\\
  

jobs:
  
  Check-Env-Variables: 
    runs-on: windows-latest
    steps:

      - name: Veify XML file
        run: ls ${workspace}
        shell: pwsh
        
      - name : Run
        run: powershell Write-Output ${solutionList} ${workspace}
        shell: cmd

      - name: Create XML file
        run: |
          $xmlWriter = New-Object System.XMl.XmlTextWriter("${workspace}\SolutionList.xml",$Null)
          $xmlWriter.Formatting = "Indented"
          $xmlWriter.Indentation = 1
          $XmlWriter.IndentChar = "`t"
          $xmlWriter.WriteStartDocument()
          $xmlWriter.WriteStartElement("build")
          $xmlWriter.WriteEndElement()
          $xmlWriter.WriteEndDocument()
          $xmlWriter.Flush()
          $xmlWriter.Close()
        shell: pwsh

      - name : Run
        run: powershell main ${solutionList} ${workspace}
        shell: cmd

      - name: Veify XML file
        run: ls ${workspace}
        shell: pwsh
