name: Solution List
on: 
  push:
    branches: [solution]

env:
  solutionList : >
    '[
    {"name":"solutionPath","path":"Project\\Build\\Licensing\\Licensing.sln","vsversion":"vs2017","usemsbuild":"false","buildconfig":"Release","buildplatform":"Win32"},
    {"name":"solutionPath","path":"Project\\Build\\Files\\WUGLibs.sln","vsversion":"vs2017","usemsbuild":"false","buildconfig":"Release","buildplatform":"Any CPU"}
    ]'
  workspace: D:\\
  

jobs:
  
  Check-Env-Variables: 
    runs-on: windows-latest
    steps:

      - name: Variables Powershell
        run: Write-Host "Solution Path-" ${{env.solutionList}}
 
        
      - name: Veify XML file
        run: ls ${Env:workspace}
      
      - name: XML Writer
        run: >
          $xmlWriter = New-Object System.XMl.XmlTextWriter("${Env:workspace}\SolutionList.xml",$Null);
          $xmlWriter.Formatting = 'Indented';
          $xmlWriter.Indentation = 1;
          $XmlWriter.IndentChar = "`t";
          $xmlWriter.WriteStartDocument();
          $xmlWriter.WriteStartElement('build');
          $xmlWriter.WriteEndElement();
          $xmlWriter.WriteEndDocument();
          $xmlWriter.Flush();
          $xmlWriter.Close();
        shell: pwsh

      - name: Add First Solution
        run: >
          $solutionListObj = ${Env:solutionList} | ConvertFrom-Json;
          foreach($solutionListNode in $solutionListObj)
          {   
            Write-Host $solutionListNode
          }


          
      - name: Read XML File
        run : cat "${Env:workspace}\SolutionList.xml"
        
        
      - name: Read XML File
        run : cat "${{env.workspace}}\SolutionList.xml"
       
      
             
      - name: Read XML File
        run : cat c:\\SolutionList.xml

        
           
      - name: Veify XML file
        run: ls ${Env:workspace}
