name: Solution List
on: 
  push:
    branches: [solution]

env:
  solutionList : >
    '[
    {"name":"solutionPath","path":"Project\\Build\\Licensing\\Licensing.sln","vsversion":"vs2017","usemsbuild":"false","buildconfig":"Release","buildplatform":"Win32"},
    {"name":"solutionPath","path":"Project\\Build\\Files\\WUGLibs.sln","vsversion":"vs2017","usemsbuild":"false","buildconfig":"Release","buildplatform":"Any CPU"}
    ]'
  workspace: D:\\
  

jobs:
  
  Check-Env-Variables: 
    runs-on: windows-latest
    steps:

      - name: Variables Powershell
        run: Write-Host "Solution Path-" ${{env.solutionList}}
 
        
      - name: Veify XML file
        run: ls ${Env:workspace}
      
      - name: XML Writer
        run: >
          $xmlWriter = New-Object System.XMl.XmlTextWriter("${Env:workspace}\SolutionList.xml",$Null);
          $xmlWriter.Formatting = 'Indented';
          $xmlWriter.Indentation = 1;
          $XmlWriter.IndentChar = "`t";
          $xmlWriter.WriteStartDocument();
          $xmlWriter.WriteStartElement('build');
          $xmlWriter.WriteEndElement();
          $xmlWriter.WriteEndDocument();
          $xmlWriter.Flush();
          $xmlWriter.Close();
        shell: pwsh

      - name: Add First Solution
        run: >
          $solutionListObj = ${Env:solutionList} | ConvertTo-Json | ConvertFrom-Json;
          $solutionListXML = [System.Xml.XmlDocument](Get-Content "${Env:workspace}\SolutionList.xml");
          foreach($solutionListNode in $solutionListObj){ Write-Host $solutionListNode.path };
          

      - name: Add First Solution
        run: >
          $solutionListObj = ${Env:solutionList} | ConvertFrom-Json;
          $solutionListXML = [System.Xml.XmlDocument](Get-Content "${Env:workspace}\SolutionList.xml");
          $root = $solutionListXML.SelectSingleNode("build");
          $newElement = $root.AppendChild($solutionListXML.CreateElement("solution"));
          $newElement.InnerText = $solutionListObj[0].path;
          $newElement.SetAttribute("vsversion",$solutionListObj[0].vsversion);
          $newElement.SetAttribute("usemsbuild",$solutionListObj[0].usemsbuild);
          $newElement.SetAttribute("buildconfig",$solutionListObj[0].buildconfig);
          $newElement.SetAttribute("buildplatform",$solutionListObj[0].buildplatform);
          $solutionListXML.Save("${Env:workspace}\SolutionList.xml");


          
      - name: Read XML File
        run : cat "${Env:workspace}\SolutionList.xml"
        
        
      - name: Read XML File
        run : cat "${{env.workspace}}\SolutionList.xml"
           
      - name: Veify XML file
        run: ls ${Env:workspace}
