name: Solution List
on: 
  push:
    branches: [solution]

env:
  solutionList : >
    '[
    {"name":"solutionPath","path":"Project\\Build\\Licensing\\Licensing.sln","vsversion":"vs2017","usemsbuild":"false","buildconfig":"Release","buildplatform":"Win32"},
    {"name":"solutionPath","path":"Project\\Build\\Files\\WUGLibs.sln","vsversion":"vs2017","usemsbuild":"false","buildconfig":"Release","buildplatform":"Any CPU"}
    ]'
  workspace: D:\\
  

jobs:
  
  Check-Env-Variables: 
    runs-on: windows-latest
    steps:

      - name: Variables Powershell
        run: Write-Host "Solution Path-" ${{env.solutionList}}
        shell: pwsh

      - name: Variables Bash
        run: echo "Solution Path- ${solutionList}"
        shell: bash
        
      - name: Veify XML file
        run: ls ${Env:workspace}
        shell: pwsh
        
      - name: XML Writer 
        run: |
          Write-Output "New-Object System.XMl.XmlTextWriter('${Env:workspace}\SolutionList.xml',$Null)" | Get-Member
        shell: pwsh
        
      - name: XML Writer
        id: XML-Writer
        run: |
          echo "::set-output name=XML-Writer-Object::$(New-Object System.XMl.XmlTextWriter("${Env:workspace}\SolutionList.xml",$Null))"
        shell: pwsh

      - name: Add Properties to XML File
        env :
          xmlWriter: ${{ steps.XML-Writer.outputs.XML-Writer-Object }}
        run: |
          "${{ steps.XML-Writer.outputs.XML-Writer-Object }}.Formatting = 'Indented'"
          "${{ steps.XML-Writer.outputs.XML-Writer-Object }}.WriteStartDocument()"
          "${{ steps.XML-Writer.outputs.XML-Writer-Object }}.Indentation = 1"
          "${{ steps.XML-Writer.outputs.XML-Writer-Object }}.IndentChar = '`t'"
          "${{ steps.XML-Writer.outputs.XML-Writer-Object }}.WriteStartElement('build')"
          "${{ steps.XML-Writer.outputs.XML-Writer-Object }}.WriteEndElement()"
          "${{ steps.XML-Writer.outputs.XML-Writer-Object }}.WriteEndDocument()"
          "${{ steps.XML-Writer.outputs.XML-Writer-Object }}.Flush()"
          "${{ steps.XML-Writer.outputs.XML-Writer-Object }}.Close()"
          
          echo "$xmlWriter"
          echo "${xmlWriter}"
          echo "${env.xmlWriter}"
          echo "${{ env.xmlWriter }}"
          
      - name: Read XML File
        run : cat "${Env:workspace}\SolutionList.xml"
        shell: pwsh
        
      - name: Read XML File
        run : cat "${{env.workspace}}\SolutionList.xml"
        shell: pwsh
      
      - name: Read XML File
        run : cat "${{env.workspace}}\SolutionList.xml"
        shell: bash
        
      - name: Read XML File
        run : cat D:\\SolutionList.xml
        shell: pwsh
        
           
      - name: Veify XML file
        run: ls ${Env:workspace}
        shell: pwsh
