name: Solution List
on: 
  push:
    branches: [solution]

env:
  solutionList : >
    '[
    {"name":"solutionPath","path":"Project\\Build\\Licensing\\Licensing.sln","vsversion":"vs2017","usemsbuild":"false","buildconfig":"Release","buildplatform":"Win32"},
    {"name":"solutionPath","path":"Project\\Build\\Files\\WUGLibs.sln","vsversion":"vs2017","usemsbuild":"false","buildconfig":"Release","buildplatform":"Any CPU"}
    ]'
  

jobs:
  
  Check-Env-Variables: 
    env:
      workspace: D:\\
    runs-on: windows-latest
    steps:
      - name: Verify Env Variables
        run: |
          Write-Host "Solution List- ${solutionList}"
          Write-Host ${workspace}
          Write-Host "${workspace}"
        shell: pwsh

