# Key: value
name: Basic Commands Workflow

# key: array[String]
# It can be 
# on : [push, pull_request] or
# on: 
#   - push
#   - pull_request
# Both are ways to define array in yaml
on:
  pull_request:
    branches: [main]

# If we check json object then it would be equivalent to:
#  {
#   jobs: {
#     checkout: {
#       runs-on : ubuntu-latest,
#       steps: 
#         [
#           { name: Checkout github code, uses: actions/checkout@v2}
#           { name: Bash Command, run: echo "Hello"}
#           { name: Working dir, run: "whoami \n dir"}
#         ]
#     }
#   }
# }

# key: Object
jobs:
  # key: Object
  Checkout:
    # key : value
    runs-on: ubuntu-latest
    # key : array[Object]
    steps:
      - name: Checkout github code
        uses: actions/checkout@v2
      - name: Bash Command
        run: echo "Hello"
      - name: Working dir
      # | combines all the below commands into one single string preserving spaces and then runs commsnd one by one
      # If we dont want to preserve spaces then replace | with >
        run: |
          whoami
          dir

  Simple-Powershell-Command:
    runs-on: windows-latest
    steps:
      - name: Powershell Command
        run: Get-Location
        shell: powershell
      - name: Bash Command
        run: pwd
        shell: bash

  Test-Suite:
    runs-on: windows-latest
    # needs: [Checkout]
    needs: 
      - Checkout
    steps:
      - name: Checkout github code
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
      - name: Install Dependencies
        run: npm i
      - name: Run Mocha Test
        run: npm run test