name: Basic Commands
on:
  - push
  - pull_request

jobs:
  
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github code
        uses: actions/checkout@v2
      - name: Bash Command
        run: echo "Hello"
      - name: Working dir
        run: |
          whoami
          cwd